### ISSUE TITLE
Able to keep playing after winner is determined

### ISSUE THREAD

**Issue by ilterates** [PJC-1/tic-tac-toe#1]
### Expected behavior

After winner is determined, player should not be able to keep playing unless game is restarted.
### Actual behavior

After winner is determined, player is still able to play in the game.
### Reproduce

Win the game and continue playing without restarting the game.

**Comment by PJC-1** [comment]
I was able to resolve the issue (better late than never!) by creating a global variable named win and initially setting it to false. Then when a game is won I can set win to true and create condition that returns false when win is equal to true, so the user is prevented from claiming an available box after the game is won.

Thanks for submitting a bug Ilter. =)
